[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "growl"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
dependencies = [
    "attrs>=26.1.0,<27",
    "docker>=7.2.0,<8",
    "h5py>=3.16.0,<4",
    "matplotlib>=3.11.1,<4",
    "numpy>=2.5.1,<3",
    "pandas>=3.0.3,<4",
    "pint>=0.25.3,<2",
    "uncertainties>=3.2.3,<4",
]

[project.scripts]
parse-compas-options = "growl.tools.parse_compas_options:main"
plot-popsynth = "growl.tools.plot_popsynth:main"

[dependency-groups]
dev = [
    "jupyterlab==4.6.4,<5",
    "pandas-stubs>=3.0.3.260530,<4",
    "prek==0.5.3,<2",
    "pyrefly>=1.3.1,<2",
    "pytest>=9.1.1,<10",
    # tornado is a transitive dependency, but it has several security issues:
    # * https://github.com/advisories/GHSA-wwv5-g3v4-889x
    # * https://github.com/advisories/GHSA-8423-8fgw-73vq
    # * https://github.com/advisories/GHSA-mpf4-983q-p7j4
    # and we have some issues with the package dependent on it:
    # https://github.com/kcsapp/pygrowl/issues/10
    # This explicit definition can be removed after revisiting jupyter dependency.
    "tornado>=6.5.8,<7",
    "types-docker>=7.2.0.20260827,<8",
]

## NOTE: The following tooling configuration can also be stored in dedicated files.
## The current agreement is to keep configuration for each tool in pyproject.toml
## until that tool's configuration reaches 20 lines in this file.
[tool.ruff]
line-length = 100

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
extend-select = [
    "E",
    "F",
    "I",
    "PTH",
]

[tool.pyproject-fmt]
indent = 4
keep_full_version = true
table_format = "long"
sub_table_spacing = "\n"
collapse_tables = [ "project.authors" ]

[tool.pyrefly]
infer-with-first-use = false
